### ISSUE TITLE
The method 'builder' isn't defined for the class 'CupertinoPicker'

### ISSUE THREAD

**Issue by ztj666** [Realank/flutter_datetime_picker#1]
child: CupertinoPicker.builder(
                  key: ValueKey(widget.pickerModel.currentMiddleIndex()),
                  backgroundColor: Colors.white,
                  scrollController: scrollController,
                  itemExtent: _kDatePickerItemHeight,
                  onSelectedItemChanged: (int index) {
                    selectedChangedWhenScrolling(index);
                  },

**Comment by Realank** [comment]
which version of flutter do you use? I'm using 0.9.3 in master channel, it works fine

**Comment by Realank** [comment]
if there's no doubt anymore, I will close this issue, if you also have problem, please feel free to create new issue or contact me, thanks
