### ISSUE TITLE
When minTime and currentTime are set to the same value, the mintime setting fails

### ISSUE THREAD

**Issue by GaoCYue** [Realank/flutter_datetime_picker#100]
```
DatePicker.showDateTimePicker(
                        context,
                        locale: LocaleType.zh,
                        currentTime: DateTime.now(),
                        minTime: DateTime.now(),
                        maxTime: DateTime.now().add(new Duration(hours: 48)),
                        onConfirm: (date) {
                          print('confirm $date');
                        },
                      );
```

When minTime and maxTime are set to the same value, the mintime setting

**Comment by Realank** [comment]
yes,That is the original logic, why you need set minTime == maxTime ?

**Comment by GaoCYue** [comment]
sorry，Sorry, the title description is wrong，What I want to express is that when mintime and currenttime are set to the same value

**Comment by valtlfelipe** [comment]
I'm having the same issue. Any update on this ?

**Comment by Realank** [comment]
hi, according to your codes:
DatePicker.showDateTimePicker(
                        context,
                        locale: LocaleType.zh,
                        currentTime: DateTime.now(),
                        minTime: DateTime.now(),
                        maxTime: DateTime.now().add(new Duration(hours: 48)),
                        onConfirm: (date) {
                          print('confirm $date');
                        },
                      );

there are 3rd times DateTime.now() invoke, these 3 DateTime.now() are different, not same. it result in minTime is later than currentTime, then minTime setting failed
