### ISSUE TITLE
Add right padding 

### ISSUE THREAD

**Issue by nailgilaziev** [Realank/flutter_datetime_picker#106]
Currently when using time mode things tight to the right very closely
No space between minutes and right side of screen
![Screen Shot 2020-01-21 at 21 30 57](https://user-images.githubusercontent.com/2749021/72832164-6295ce80-3c95-11ea-9b27-0126abad6abc.png)

Thanks!

**Comment by nailgilaziev** [comment]
Top and bottom margin is not configurable too ( 
Cropping is not very good.

**Comment by Realank** [comment]
you can customize your own picker model and override layoutProportions method to specify how much space every column should be.

@override
  List<int> layoutProportions() {
    return [1, 2, 1];
  }

for top and bottom margin, yes it can't config, it iOS style

**Comment by nailgilaziev** [comment]
Convenient function `showDatePicker` internally uses private `_DatePickerRoute`
```
static Future<DateTime> showDatePicker(
    BuildContext context, {
    bool showTitleActions: true,
    DateTime minTime,
    DateTime maxTime,
    DateChangedCallback onChanged,
    DateChangedCallback onConfirm,
    locale: LocaleType.en,
    DateTime currentTime,
    DatePickerTheme theme,
  }) async {
    return await Navigator.push(
        context,
        new _DatePickerRoute(
            showTitleActions: showTitleActions,
            onChanged: onChanged,
            onConfirm: onConfirm,
            locale: locale,
            theme: theme,
            barrierLabel:
                MaterialLocalizations.of(context).modalBarrierDismissLabel,
            pickerModel: DatePickerModel(
                currentTime: currentTime,
                maxTime: maxTime,
                minTime: minTime,
                locale: locale)));
  }
```
So it not so convenient to use own DatePickerModel. 

@Realank , Maybe need exposing some API for using from `showDatePicker` function?

**Comment by vankhoa01** [comment]
Hi @nailgilaziev
How can you hide divider line here ?

Thank a lot
<img width="312" alt="Screen Shot 2020-11-26 at 13 41 34" src="https://user-images.githubusercontent.com/8953129/100316484-2fc31200-2fed-11eb-8ab4-391a8d3d88a7.png">
