### ISSUE TITLE
RTL support for timePicker

### ISSUE THREAD

**Issue by alizera** [Realank/flutter_datetime_picker#110]
I'm using TimePicker as follow:
```
    DatePicker.showTimePicker(
      context,
      locale: LocaleType.fa
    ).then((value) => {print(value)});
```

And this is the result:
![image](https://user-images.githubusercontent.com/50444607/73745854-3b490200-4769-11ea-9ab2-935d183d5b21.png)

**Problem:**
1- The format is not H:M:S and is S:M:H (made numbers RTL that must not do)
2- Top buttons has NOT margin
3- It would be better to add `TextStyle` for numbers (if it's possible)

**Comment by Realank** [comment]
thanks for your question,

for question 1: you can customize your own picker model to achieve that, you can refer to readme
for question 2: you can add space to your "confirm"/"cancel" string to workaround
for question 3: you can specify itemStyle in DatePickerTheme
