### ISSUE TITLE
[Question] How to use custom font familly?

### ISSUE THREAD

**Issue by Gausoft** [Realank/flutter_datetime_picker#113]
Is it possible to change the default font familly ?
How Can I do that?

**Comment by aadarsh-patel** [comment]
> 
> 
> Is it possible to change the default font familly ?
> How Can I do that?

Yes.
You can use custom fonts as many as you want.
[here](https://flutter.dev/docs/cookbook/design/fonts) is link from the official flutter website showing how to do the same.
