### ISSUE TITLE
Change Date Format

### ISSUE THREAD

**Issue by FabricioMedeiros** [Realank/flutter_datetime_picker#114]
Hello, 

how Can I change the format to user select the date ? Default is YYYY MM DD , I'd like to change to DD MM YYYY.

My code :

 DatePicker.showDatePicker(context,
                        showTitleActions: true,
                        minTime: DateTime(1960, 1, 1),
                        maxTime: DateTime(2099, 12, 31), onConfirm: (date) {
                      _dateSelected = dateFormat.format(date);

                      setState(() {
                        _editedClient.dateOfBirth = _dateSelected;
                      });
                    }, currentTime: DateTime.now(), locale: LocaleType.pt);

**Comment by Realank** [comment]
you can customize your own picker model to achieve that, please refer to readme
