### ISSUE TITLE
请问支持 时分【秒】的选择吗？

### ISSUE THREAD

**Issue by ruiq** [Realank/flutter_datetime_picker#118]
请教老哥，这个控件支持到 秒 级的选择吗？比如datetimepicker，现在是左边年月日，右边是时分，但是没有秒的选择。是我没找到还是不支持？
感谢回复。

**Comment by Realank** [comment]
年月日时分的选择，是iOS默认风格，如果需要选择时分秒，有时间选择器。如果既想选择日期，也想选择时分秒，目前能支持的就是先用日期选择器选择日期，再用时间选择器选择时分秒，因为此包只支持三列显示
