### ISSUE TITLE
Build error Diagnosticable

### ISSUE THREAD

**Issue by mehmet-hakan-yazkan** [Realank/flutter_datetime_picker#120]
Pub/Cache/hosted/pub.dartlang.org/flutter_datetime_picker-1.3.5/lib/src/datetime_picker_theme.dart:4:7: Error: The type 'Diagnosticable' can't be used as supertype.

$ flutter doctor -v
[√] Flutter (Channel master, v1.15.21-pre.2, on Microsoft Windows [Version 10.0.17763.1039], locale de-DE)
    • Flutter version 1.15.21-pre.2 at D:\flutter
    • Framework revision 210f4d8313 (2 hours ago), 2020-03-11 10:03:05 -0700
    • Engine revision 0e2c8feeeb
    • Dart version 2.8.0 (build 2.8.0-dev.12.0 9983424a3c)

[√] Android toolchain - develop for Android devices (Android SDK version 28.0.3)
    • Android SDK at C:\Users\memoo\AppData\Local\Android\sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-29, build-tools 28.0.3
    • Java binary at: D:\Android Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 1.8.0_212-release-1586-b04)
    • All Android licenses accepted.

[√] Chrome - develop for the web
    • Chrome at C:\Program Files (x86)\Google\Chrome\Application\chrome.exe

[√] Android Studio (version 3.6)
    • Android Studio at D:\Android Studio
    • Flutter plugin version 44.0.2
    • Dart plugin version 192.7761
    • Java version OpenJDK Runtime Environment (build 1.8.0_212-release-1586-b04)

[√] VS Code (version 1.42.1)
    • VS Code at C:\Users\memoo\AppData\Local\Programs\Microsoft VS Code
    • Flutter extension version 3.8.1

[√] Connected device (3 available)
    • SM A505F   • RZ8M74QGHPW • android-arm64  • Android 9 (API 28)
    • Chrome     • chrome      • web-javascript • Google Chrome 80.0.3987.132
    • Web Server • web-server  • web-javascript • Flutter Tools

• No issues found!

**Comment by derohimat** [comment]
I get this issue like you

**Comment by EricPreventa** [comment]
Likewise, using the latest Flutter Master build, this is a problem. Didn't have it on the beta build.

**Comment by weiyinqing** [comment]
我也是这个问题，Flutter Master是同样的版本

**Comment by weiyinqing** [comment]
I get this issue like you

**Comment by vinhcuong** [comment]
Aggryyyyy when i update Flutter i get same issue. I wish i don't update Flutter

**Comment by xXUlquiXx** [comment]
So? how we can solve this problem? i need to upload an update off my app and i'm stuck with this.

**Comment by derohimat** [comment]
I fix this issue with this [Diagnosticable to DiagnosticableMixin](https://github.com/derohimat/flutter_datetime_picker/commit/022d446b52331d6d5f8e7e516c5ed830cd49a1b2)
