### ISSUE TITLE
Compilation Error 

### ISSUE THREAD

**Issue by yeras-is** [Realank/flutter_datetime_picker#135]
Compiler message:
../../AppData/Roaming/Pub/Cache/hosted/pub.dartlang.org/flutter_datetime_picker-1.3.5/lib/src/datetime_picker_theme.dart:15:9: Error: The superclass, 'Diagnosticable', has no unnamed constructor that takes no arguments.
  const DatePickerTheme({
        ^^^^^^^^^^^^^^^
Unhandled exception:
NoSuchMethodError: The getter 'name' was called on null.
Receiver: null
Tried calling: name
#0      Object.noSuchMethod  (dart:core-patch/object_patch.dart:53:5)

**Comment by hrashdan** [comment]
Same Here :

`Compiler message:
../../AppData/Local/Pub/Cache/hosted/pub.dartlang.org/flutter_datetime_picker-1.3.5/lib/src/datetime_picker_theme.dart:15:9: Error: The superclass, 'Diagnosticable', has no unnamed constructor that takes no arguments.
  const DatePickerTheme({
        ^^^^^^^^^^^^^^^
Application finished.`

![image](https://user-images.githubusercontent.com/46036841/78901086-7d036b00-7a80-11ea-8ed3-ab672e3812ac.png)

**Comment by hrashdan** [comment]
fix it change the line 4 of (flutter_datetime_picker/lib/src/datetime_picker_theme.dart)
from 
`class DatePickerTheme extends Diagnosticable {`
to
`class DatePickerTheme with DiagnosticableMixin  {`

___________________________________________________________________________

**Or** simply change your (pubspec.yaml)
**From**
 `flutter_datetime_picker: ^1.3.5`

**To**
```
  flutter_datetime_picker:
    git:
      url: https://github.com/Realank/flutter_datetime_picker.git
```

**Comment by yeras-is** [comment]
@hrashdan  thx a lot, dev channel was broken for 1 day 0.0

**Comment by iulianoana** [comment]
Same issue here. Fixed it with @hrashdan 's suggestions. Thanks!
I'd be good to see the change released.

**Comment by Realank** [comment]
This issue has been fixed, please try latest codes, thanks
