### ISSUE TITLE
Problems in the Persian calendar

### ISSUE THREAD

**Issue by jepbura** [Realank/flutter_datetime_picker#136]
Hi
In the Persian calendar, it is now 1399
But
It shows 2020
I use the version flutter_datetime_picker 1.3.5

` DatePicker.showDatePicker(context,
                                showTitleActions: true,
                                minTime: DateTime(1398, 12, 25),
                                maxTime: DateTime(1470, 12, 25),
.
.
.`

`currentTime: DateTime.now(),
                              locale: LocaleType.fa);`

**Comment by MojtabaTavakkoli** [comment]
It might be causing of your app localization. Try to set your app localization to your region. Here's some example:


```
import 'package:flutter_localizations/flutter_localizations.dart';
import 'package:flutter/material.dart';


void main() => runApp(MaterialApp(



  localizationsDelegates: [
    GlobalMaterialLocalizations.delegate,
    GlobalWidgetsLocalizations.delegate,
  ],
  supportedLocales: [
    Locale("fa", "IR"),
  ],
  locale: Locale("fa", "IR"),
  debugShowCheckedModeBanner: false,

  home: MyApp(),
));
```


And remember to add flutter localization in your `pubspec.yaml` file.

> 
> 
> Hi
> In the Persian calendar, it is now 1399
> But
> It shows 2020
> I use the version flutter_datetime_picker 1.3.5
> 
> ` DatePicker.showDatePicker(context, showTitleActions: true, minTime: DateTime(1398, 12, 25), maxTime: DateTime(1470, 12, 25), . . .`
> 
> `currentTime: DateTime.now(), locale: LocaleType.fa);`

**Comment by Realank** [comment]
sorry, we can't support Persian calendar, the year should be greater than 1970
