### ISSUE TITLE
DiagnosticableMixin not found

### ISSUE THREAD

**Issue by lmanliang** [Realank/flutter_datetime_picker#155]
../../AppData/Roaming/Pub/Cache/hosted/pub.dartlang.org/flutter_datetime_picker-1.3.8/lib/src/datetime_picker_theme.dart:6:28: Error: Type 'DiagnosticableMixin' not found.
class DatePickerTheme with DiagnosticableMixin {
                           ^^^^^^^^^^^^^^^^^^^
../../AppData/Roaming/Pub/Cache/hosted/pub.dartlang.org/flutter_datetime_picker-1.3.8/lib/src/datetime_picker_theme.dart:6:7: Error: The type 'DiagnosticableMixin' can't be mixed in.
class DatePickerTheme with DiagnosticableMixin {

**Comment by jacky-yanglei** [comment]
![ecdf40ab3a24fa92d55303b17354fc5](https://user-images.githubusercontent.com/17645850/84849116-371de100-b087-11ea-9c60-796ad7823785.png)

![image](https://user-images.githubusercontent.com/17645850/84849174-54eb4600-b087-11ea-9504-3ad56cf5983d.png)

flutter update remove DiagnosticableMixin

**Comment by jacky-yanglei** [comment]
> ../../AppData/Roaming/Pub/Cache/hosted/pub.dartlang.org/flutter_datetime_picker-1.3.8/lib/src/datetime_picker_theme.dart:6:28: Error: Type 'DiagnosticableMixin' not found.
> class DatePickerTheme with DiagnosticableMixin {
> ^^^^^^^^^^^^^^^^^^^
> ../../AppData/Roaming/Pub/Cache/hosted/pub.dartlang.org/flutter_datetime_picker-1.3.8/lib/src/datetime_picker_theme.dart:6:7: Error: The type 'DiagnosticableMixin' can't be mixed in.
> class DatePickerTheme with DiagnosticableMixin {

flutter update remove DiagnosticableMixin

**Comment by lmanliang** [comment]
so cant fix this error , right?

**Comment by jacky-yanglei** [comment]
> so cant fix this error , right?
You can modify the DiagnosticMixin in the library to Diagnostic

**Comment by mzkai** [comment]
After the most recent Flutter update, changing 'DiagnosticMixin' to 'Diagnostic' indeed solves the problem. Thanks @jacky-yanglei!

The **flutter_datetime_picker** package should now be updated with the same.

**Comment by nsjcorps** [comment]
I had this issue too but it was solved by @jacky-yanglei 's suggestion. Thanks

**Comment by lcsvcn** [comment]
Will this be released in a V.1.3.9 any soon? I am having issues as well.

**Comment by lcsvcn** [comment]
DiagnosticMixin in the library to Diagnosticable, not Diagnostic

**Comment by valterh4ck3r** [comment]
Same issue

**Comment by NumanIbnMazid** [comment]
Same Issue.
flutter/.pub-cache/hosted/pub.dartlang.org/flutter_datetime_picker-1.3.8/lib/src/datetime_picker_theme.dart:6:7: Error: The type 'DiagnosticableMixin' can't be mixed in.
class DatePickerTheme with DiagnosticableMixin {

**Comment by kebsont** [comment]
For me I replace all DiagnosticableMixin in the class by Diagnosticable and it works

**Comment by Abhishekhm777** [comment]
Error: Type 'DiagnosticableMixin' not found.
class PictureStream with DiagnosticableMixin {

**Comment by m-takata** [comment]
Same issue.

**Comment by ahrasel** [comment]
same issue.
any solution?

**Comment by Bforsyth1234** [comment]
FYI there is a PR to fix this. You can use it now by putting this in your pubspec.yaml

```
 flutter_datetime_picker:
   git:
     url: https://github.com/ditheshthegreat/flutter_datetime_picker # Repo
     ref: patch-1 # Branch name
 ```

pr-> https://github.com/Realank/flutter_datetime_picker/pull/158

**Comment by thenexus00** [comment]
> FYI there is a PR to fix this. You can use it now by putting this in your pubspec.yaml
> 
> ```
>  flutter_datetime_picker:
>    git:
>      url: https://github.com/ditheshthegreat/flutter_datetime_picker # Repo
>      ref: patch-1 # Branch name
> ```
> 
> pr-> #158

Thank you, this helped get my build running after the recent flutter updates that just broke nearly everything and this was the last thing to get it going.

**Comment by Realank** [comment]
Done

**Comment by fnicastri** [comment]
> Done
@Realank 
Thanks!

**Comment by Anup134638** [comment]
To solve this is done the following updates in pubspec.yaml
Flutter_svg: ^0.18.0
flutter_html: ^1.0.2
flutter_widget_from_html: 0.4.3

**Comment by shinriyo** [comment]
@the-anup-das 

`Flutter_svg`? Not `flutter_svg`?

`dnfield/flutter_svg` is needed?


it works for me.

```
dependencies:
  flutter_datetime_picker: ^1.4.0
```

**Comment by the-anup-das** [comment]
> 
> 
> @the-anup-das
> 
> `Flutter_svg`? Not `flutter_svg`?
> 
> `dnfield/flutter_svg` is needed?
> 
> it works for me.
> 
> ```
> dependencies:
>   flutter_datetime_picker: ^1.4.0
> ```
Yeah you are right! thanks for seeing it.

**Comment by hiashutoshsingh** [comment]
> For me I replace all DiagnosticableMixin in the class by Diagnosticable and it works

how ?

**Comment by kebsont** [comment]
@hiashutoshsingh with Ctrl+F
Search and replace

**Comment by hiashutoshsingh** [comment]
> @hiashutoshsingh with Ctrl+F
> Search and replace

but that class in cache file of package is it recommended to modify files in package ?

**Comment by Luvti** [comment]
> > @hiashutoshsingh with Ctrl+F
> > Search and replace
> 
> but that class is in cache file of package...is it recommended to modify files in package ?

use this fix instead: https://github.com/Luvti/flutter_datetime_picker/commit/6f70dd51bada86c799501ab605a300cfa994a905

**Comment by kebsont** [comment]
> > @hiashutoshsingh with Ctrl+F
> > Search and replace
> 
> but that class is in cache file of package...is it recommended to modify files in package ?

It is not recommended if you don’t know what you are doing. 
Search and replace the name of the class and it will works
