### ISSUE TITLE
Minimum steps in time selection fields

### ISSUE THREAD

**Issue by makemydayrubberduck** [Realank/flutter_datetime_picker#16]
Hello, is it possible to customise the minimum "steps" or "jumps" in the time selection fields?

For example, I would like to display the minutes field in increments of 30 minutes:

[Today] [13] [30]
[Today] [14] [00]
[Today] [14] [30]
[Today] [15] [00]

Currently, the minutes field instead displays:

[Today] [13] [30]
[Today] [13] [31]
[Today] [13] [32]
[Today] [13] [33]

Would it be possible to set a minimum time increment?

**Comment by Realank** [comment]
sure, it can by implemented by your custom DateTime model, just extents CommonPickerModel, and write your own model refer to TimerPicker

**Comment by temirfe** [comment]
@makemydayrubberduck
Have you done it? Can you show an example please?
