### ISSUE TITLE
Please change DiagnosticableMixin class back to Diagnosticable

### ISSUE THREAD

**Issue by yuva-dev** [Realank/flutter_datetime_picker#166]
With flutter 1.20 Diagnosticable Mixin needs to be changed back to Diagnosticable

**Comment by nstrelow** [comment]
Please change, this is affecting me when using https://github.com/danvick/flutter_form_builder

**Comment by nwparker** [comment]
See 158

**Comment by kmh339** [comment]
same..

**Comment by Realank** [comment]
thanks, fixed
