### ISSUE TITLE
Error in Flutter1.20

### ISSUE THREAD

**Issue by tongyangsheng** [Realank/flutter_datetime_picker#168]
When I update my Flutter version to 1.20, i can‘t run my project，because error <br/>
../../../../../../development/flutter/.pub-cache/hosted/pub.dartlang.org/flutter_datetime_picker-1.3.8/lib/src/datetime_picker_theme.dart:6:28: Error: Type 'DiagnosticableMixin' not found.
class DatePickerTheme with DiagnosticableMixin {
                           ^^^^^^^^^^^^^^^^^^^
../../../../../../development/flutter/.pub-cache/hosted/pub.dartlang.org/flutter_datetime_picker-1.3.8/lib/src/datetime_picker_theme.dart:6:7: Error: The type 'DiagnosticableMixin' can't be mixed in.
class DatePickerTheme with DiagnosticableMixin {
      ^
Any help?

**Comment by shubh-151410** [comment]
yes, i am face same issues

**Comment by carmas123** [comment]
Edit the source code (for now, awaiting the release) and replace `DiagnosticableMixin` with `DiagnosticableTreeMixin`

**Comment by connlaoi** [comment]
@carmas123 That solution works as well, however the source actually notes that it will be switching to "Diagnosticable" and not the *TreeMixin variant. Not sure if this will have any consequences once it is updated. But figured it was worth mentioning. 🤷‍♂️ 

```
// Migrate DiagnosticableMixin to Diagnosticable until
// https://github.com/flutter/flutter/pull/51495 makes it into stable (v1.15.21)
class DatePickerTheme with Diagnosticable {
...
}
```

**Comment by guohuanle** [comment]
same issues

**Comment by tongyangsheng** [comment]
Thanks @carmas123 ,I have already fixed it by replacing `DiagnosticableMixin`  with `DiagnosticableTreeMixin`
![image](https://user-images.githubusercontent.com/32046282/89600834-97feb400-d895-11ea-85d6-76bce018393e.png)

**Comment by connlaoi** [comment]
> same issues

You might want to try flutter clean and flutter upgrade.

Can you provide more insight into your issue?

**Comment by maerlynflagg** [comment]
Same build issue after upgrading to Flutter 1.20.1 today. 

is there any side effect to change DiagnosticableMixin to the other one?

**Comment by Realank** [comment]
Thanks for your help. I've fixed this issue
