### ISSUE TITLE
Error in Flutter1.20,please update flutter_datetime_picker

### ISSUE THREAD

**Issue by guohuanle** [Realank/flutter_datetime_picker#170]
Now the version after 1.20 is not available. The temporary solution is to modify the source code and change "DiagnosticableMixin" to "DiagnosticableTreeMixin" so that both the new version and the old version are available. I don’t know if this modification is correct, I hope to update the version as soon as possible (some people say it can be changed to "Diagnosticable", but this only solves the problem of the new version of the SDK, the old version of the SDK is not compatible)

**Comment by Realank** [comment]
thanks, fixed

**Comment by AlirezaDaryani** [comment]
Same issue for me ...
