### ISSUE TITLE
Add Czech language

### ISSUE THREAD

**Issue by vanicekv** [Realank/flutter_datetime_picker#171]
Please add czech language to i18n_model.dart:

  'cs': {
    'cancel': 'Zrušit',
    'done': 'Potvrdit',
    'today': 'Dnes',
    'monthShort': [
      'led',
      'úno',
      'bře',
      'dub',
      'kvě',
      'čvn',
      'čvc',
      'srp',
      'zář',
      'říj',
      'lis',
      'pro'
    ],
    'monthLong': [
      'leden',
      'únor',
      'březen',
      'duben',
      'květen',
      'červen',
      'červenec',
      'srpen',
      'září',
      'říjen',
      'listopad',
      'prosinec'
    ],
    'day': ['po', 'út', 'st', 'čt', 'pá', 'so', 'ne'],
    'am': 'AM',
    'pm': 'PM'
  },

Thanks!

**Comment by RicardoRB** [comment]
Why just don't create a pull request?

**Comment by vanicekv** [comment]
I am sorry. In any case, it is no longer relevant - we used another solution.
