### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by michael-shields** [Realank/flutter_datetime_picker#200]
Since last weekend your package has been reporting an error on the flutter_master channel.  I have been working on the beta channel figuring it would be resolved but it has not.  I have included the error message below:

![image](https://user-images.githubusercontent.com/35579717/99080946-05ef0180-2590-11eb-8b60-8e96da6489b8.png)

../../.pub-cache/hosted/pub.dartlang.org/flutter_datetime_picker-1.4.0/lib/flutter_datetime_picker.dart:215:48: Error: No named parameter with the name 'shadowThemeOnly'.
    ThemeData inheritTheme = Theme.of(context, shadowThemeOnly: true);
                                               ^^^^^^^^^^^^^^^
../../flutter/packages/flutter/lib/src/material/theme.dart:119:20: Context: Found this candidate, but the arguments don't match.
  static ThemeData of(BuildContext context) {
                   ^^
Failed to compile application.

**Comment by princefarming** [comment]
Seems the latest version of Flutter has removed that option(shadowThemeOnly), I bet this bites a bunch of packages.
