### ISSUE TITLE
Timepicker with 15 minute intervals

### ISSUE THREAD

**Issue by dev-regah** [Realank/flutter_datetime_picker#201]
Hi, I wanna set the timepicker's minute spinner collection to [0, 15, 30, 45] ie 15 min intervals. Is that possible? thanks.

**Comment by PatrickRic** [comment]
Hi, you need to make your own custom picker model, to do that. You can just copy the basic code for it from the example. Then you need to make a few changes. (I will assume that your minute column is the middle column)

1) In the constructor, change this.setMiddleIndex(this.currentTime.minute); to this.setMiddleIndex(this.currentTime.minute ~/ 15);

2) In the middleStringAtIndex method, change the if statement to (index >= 0 && index < 4) and the return statement to return this.digits(index * 15, 2);

3) In the finalTime method, change this.currentMiddleIndex() to this.currentMiddleIndex() * 15. (it appears two times in this method, change both of them)

Now, it should work like you want it to.

**Comment by dev-regah** [comment]
> Hi, you need to make your own custom picker model to do that. You can just copy the basic code for it from the example (https://pub.dev/packages/flutter_datetime_picker/example). Then you need to make a few changes. (I will assume that your middle column is the minute column)
> 
> 1. In the constructor, change this.setMiddleIndex(this.currentTime.minute); to this.setMiddleIndex(this.currentTime.minute ~/ 15);
> 2. In the middleStringAtIndex method, change the if statement to (index >= 0 && index < 4) and the return statement to return this.digits(index * 15, 2);
> 3. In the finalTime method, change this.currentMiddleIndex() to this.currentMiddleIndex() * 15. (it appears two times in this method, change both of them)
> 
> Now, it should work like you want it to.
> 
> Of course, you could also make an array with the values and instead of the index*15 you could write array[index] and instead of ~/ 15 you could use indexOf.

**Comment by dev-regah** [comment]
@PatrickRic 
Thank you for your info and explanations.
