### ISSUE TITLE
Migrate to sound null safety

### ISSUE THREAD

**Issue by lcsvcn** [Realank/flutter_datetime_picker#222]
Description:

- Migrate to sound null safety
- Bump up package version

**Comment by hhtokpinar** [comment]
Any update is coming soon to sound null safety?

**Comment by aalloul** [comment]
+1 for sound null safety

**Comment by Klazyo** [comment]
Oh boy oooo Boy  need this very fast

**Comment by roma7481** [comment]
same here, I really depend on it

**Comment by AlexHartford** [comment]
Someone has kindly opened a PR for this issue. Use this in your pubspec.yaml for now until it's merged (it could be awhile).
```dart
flutter_datetime_picker:
    git:
      url: https://github.com/figengungor/flutter_datetime_picker.git
      ref: null_safety_feature
```

**Comment by yanivshaked** [comment]
@Realank How soon can this be merged to a new release?
Thanks!
