### ISSUE TITLE
null safe  

### ISSUE THREAD

**Issue by StanleyCocos** [Realank/flutter_datetime_picker#301]
flutter_datetime_picker.dart:311:32:
 Warning: Operand of null-aware operation '??' has type 'Color' which excludes null.
 - 'Color' is from 'dart:ui'.
                  color: theme.backgroundColor ?? Colors.white,

**Comment by motucraft** [comment]
same issue.

```
../../../../../../flutter/.pub-cache/hosted/pub.dartlang.org/flutter_datetime_picker-1.5.1/lib/flutter_datetime_picker.dart:311:32: Warning: Operand of null-aware operation '??' has type 'Color' which excludes null.
 - 'Color' is from 'dart:ui'.
                  color: theme.backgroundColor ?? Colors.white,
                               ^
```

**Comment by mikhael28** [comment]
@Realank same issue here. It's the only null-safe warning in my app now :/

**Comment by ahmednfwela** [comment]
We have a fork up and running that's compatible with flutter 3.10
https://github.com/Bdaya-Dev/flutter_datetime_picker
https://pub.dev/packages/flutter_datetime_picker_bdaya
