### ISSUE TITLE
UI界面异常

### ISSUE THREAD

**Issue by c007136** [Realank/flutter_datetime_picker#31]
在本人的魅族m2 note和小米NOTE LTE都会出现图中的界面异常现象
![WechatIMG56](https://user-images.githubusercontent.com/5415898/56256685-53796300-60fc-11e9-9ac0-d7b0b0bc6dc6.jpeg)

本人代码

```
DatePicker.showDatePicker(context,
                showTitleActions: true,
                maxTime: DateTime.now(),
                minTime: DateTime(2000, 1, 1),
                locale: LocaleType.zh,
                onConfirm: (DateTime date) {
                  _timeString = DateFormat('yyyy-MM-dd').format(date);
                  _timestamp = date.millisecondsSinceEpoch;
                  print('timestamp is $_timestamp');
                  setState(() {});
                }
            );
```

**Comment by Realank** [comment]
你的flutter是最新版本吗？

**Comment by c007136** [comment]
Flutter 1.4.13-pre.6 • channel master • https://github.com/flutter/flutter.git
Framework • revision e5722f32e4 (8 days ago) • 2019-04-09 03:09:41 -0400
Engine • revision 8a46559653
Tools • Dart 2.2.1 (build 2.2.1-dev.3.1 None)

**Comment by Realank** [comment]
版本挺新的，你直接跑我的example有问题吗？我这边用小米8和iPhone6s试过都没问题，我这没有你说的两个手机

**Comment by c007136** [comment]
下载了你的example，在master分支上依旧有问题，切换到stable分支，就正常了。
不知道能不能在你的手机上尝试下，是不是也这样呢？
另外本人之所以切换成master分支，是因为小米NOTE LTE手机在stable分支上运行flutter的所有代码都会崩溃，故不知道能不能帮忙解决下这个问题呢？

**Comment by Realank** [comment]
我的就是master分支。那问题就明朗了，这是flutter sdk的问题。这我就无能为力了，建议去flutter的repo上提英文issue，他们好知道这个情况

**Comment by c007136** [comment]
在master分支上UI异常，应该不属于flutter sdk的问题吧....

**Comment by c007136** [comment]
还真是flutter sdk的问题，今天升级了下master分支就OK了，十分抱歉啊
