### ISSUE TITLE
关于可以设置时间范围的建议

### ISSUE THREAD

**Issue by DNetORM** [Realank/flutter_datetime_picker#33]
DatePicker.showDateTimePicker中 我想讲小时和分钟部分做个限制 比如只能选08:00到21:00的时间范围，可以完善下么，这个很常用的场景，比如我的作业时间就是在08:00到21:00这个范围内，所以希望别人选时间的时候就得选择这个范围之内的时间

**Comment by DNetORM** [comment]
比如我系统里设置的工作时间是08:00-21:00，就是这个范围，工人会填写他的完成某个作业的时间，我希望时间部分就限制在08:00-21:00这个范围内，22:00让他无法选到

**Comment by DNetORM** [comment]
DatePicker.showDateTimePicker是否可以扩展两个时间范围的参数 比如08:00 和21:00？

**Comment by Realank** [comment]
你好，每个用户都有不同的要求，无法一一满足，如readme所说，你可以自己定制model，传入picker，超级简单就可以实现你的功能

**Comment by DNetORM** [comment]
奥 好的 请问关于你说的可以传入自己定制的model 有demo么？

**Comment by Realank** [comment]
继承CommonPickerModel即可实现，Demo就是其它PickerModel，比如TimerPickerModel和你的需求很贴近
