### ISSUE TITLE
AM/PM?

### ISSUE THREAD

**Issue by rgbinnovation** [Realank/flutter_datetime_picker#37]
Can the plugin display AM/PM? I am looking to use the plugin to show hours, minutes and am/pm only. The documentation does not mention this, and I can't seem to see an option for it?

**Comment by Realank** [comment]
Hi, yes, we didn't support this option by default, but as mentioned in readme, you can extends your own model to show any data with 3 columns, just create a new class that extends CommonPickerModel, fill some methods (reference to TimePickerModel), and it will meet your demand

**Comment by ziggycrane** [comment]
It's pretty basic functionality that "DateTime" picker SHOULD support.

**Comment by ziggycrane** [comment]
Because now, every single one who uses this library to pick time needs to create their own custom solution to support US and other users ...

**Comment by Realank** [comment]
Thanks for your strong suggestion, I have added this feature, try showTime12hPicker method in 1.3.5 version, 😄

**Comment by rgbinnovation** [comment]
Thanks!!!
