### ISSUE TITLE
关于datetimepicker 小时分钟的范围

### ISSUE THREAD

**Issue by DNetORM** [Realank/flutter_datetime_picker#39]
这个问题之前提到过 后来作者建议我继承CommonPickerModel去实现 今天我继承了这个类，小时部分可以控制一个范围，比较容易，但是分钟部分我控制起来就有点难，不知道怎么控制，比如我的时间范围是8:30到20:30，当我选到20的时候分钟最大只能到30，我选择19分钟最大是60，交互的时候不知道怎么去控制？

**Comment by Realank** [comment]
这个就看你自己的编码思路了，比如在小时的回调setLeftIndex里判断一下
