### ISSUE TITLE
CommonPickerModel is not public

### ISSUE THREAD

**Issue by rdev-software** [Realank/flutter_datetime_picker#40]
How exactly we can customize it, if main class is not public and variables controlling date picker are private ?

I mean I can extend model, but I cannot access private params such as:

   ```
 _currentLeftIndex = 0;
 _currentMiddleIndex = this.currentTime.hour;
 _currentRightIndex = this.currentTime.minute;
```

So please change it add add customisation docs

**Comment by Realank** [comment]
yes, properties with _ are private, but you can override methods defined in BasePickerModel

**Comment by rdev-software** [comment]
Ok will try that, thx
