### ISSUE TITLE
Danish language

### ISSUE THREAD

**Issue by joknjokn** [Realank/flutter_datetime_picker#41]
Danish translation. Usually months/days are with lowercase letters in danish sentences, but if you feel like a capital first letter is appropriate, then it's fine.

  'da': {
    //Danish
    'cancel': 'Annullér',
    'done': 'OK',
    'today': 'I dag',
    'monthShort': [
      'jan',
      'feb',
      'mar',
      'apr',
      'maj',
      'juni',
      'juli',
      'aug',
      'sept',
      'okt',
      'nov',
      'dec'
    ],
    'monthLong': [
      'januar',
      'februar',
      'marts',
      'april',
      'maj',
      'juni',
      'juli',
      'august',
      'september',
      'oktober',
      'november',
      'december'
    ],
    'day': ['man', 'tirs', 'ons', 'tors', 'fre', 'lør', 'søn'],
    'am': 'AM',
    'pm': 'PM'
  },
};

**Comment by Realank** [comment]
added
