### ISSUE TITLE
DatePicker.showTimePicker with only hh : mm

### ISSUE THREAD

**Issue by GauravPatni** [Realank/flutter_datetime_picker#45]
Hi ,

Is there any way to show DatePicker.showTimePicker with only **hh: mm** i.e without seconds?

Thanks,
Gaurav

**Comment by bkmza** [comment]
Hello, here is a custom setup to hide third column based on the TimeModel:

```dart
class TimeHHmmPickerModel extends TimePickerModel {
  @override
  String rightDivider() {
    return "";
  }

  @override
  List<int> layoutProportions() {
    return [100, 100, 1];
  }
}

```
Need to run method `DatePicker.showPicker` and set instance of the custom model.

**Comment by Realank** [comment]
@bkmza thanks for your work around, it's quite smart

@GauravPatni this package can only show 3 columns, 2 columns are not supported, so you can fork this codes to modify it, or use bkmza's work around, thanks
