### ISSUE TITLE
Change color of text field underline and reset icon

### ISSUE THREAD

**Issue by jasondemorrow** [Realank/flutter_datetime_picker#46]
Hi,
Thanks for publishing such a great widget. Can you add an option for specifying the color of the underline and icon colors in the text field? Or tell me how this can be done? I've tried all the standard methods like wrapping DateTimePickerFormField in a Theme, but so far nothing has worked.

**Comment by Realank** [comment]
sorry, there is no text field and icon in this package, so I don't know whose color you want to specify. However, there is a class called DatePickerTheme, you can customize it and pass it to date time picker

**Comment by jasondemorrow** [comment]
I mean the text field/icon in the date-time picker itself
