### ISSUE TITLE
Navigator.pop()冲突

### ISSUE THREAD

**Issue by YQjiuhao** [Realank/flutter_datetime_picker#47]
onPressed: () {
                if (widget.route.onConfirm != null) {
                  widget.route.onConfirm(widget.pickerModel.finalTime());
                }
                Navigator.pop(context);
              },
应该改为
onPressed: () {
                Navigator.pop(context);
                if (widget.route.onConfirm != null) {
                  widget.route.onConfirm(widget.pickerModel.finalTime());
                }
              },

**Comment by Realank** [comment]
能解释下为什么吗？调换顺序解决什么冲突？

**Comment by Realank** [comment]
我知道什么问题了，已经修改，多谢
