### ISSUE TITLE
the color of the "done" button

### ISSUE THREAD

**Issue by crazy365966834** [Realank/flutter_datetime_picker#5]
in the file "flutter_datetime_picker.dart " line of 366. the code is 
"color: Theme.of(context).primaryColor,'
then the explain of "primaryColor" in ThemeData's api:
“The background color for major parts of the app (toolbars, tab bars, etc)”
link: https://docs.flutter.io/flutter/material/ThemeData/primaryColor.html
it's really ok for use "background color for major parts of the app " to the button text?

**Comment by Realank** [comment]
I think the button in date time picker is a sort of bar button, and since I change Primary color to custom,  I prefer to use this color, which color you prefer?

**Comment by crazy365966834** [comment]
我这边做了一些调整。你看看是否可以采纳。已经发起request了

**Comment by Realank** [comment]
okay, thanks , we discuss in PR
