### ISSUE TITLE
Documentation for Creating a custom picker is not present

### ISSUE THREAD

**Issue by ZacharyEilers** [Realank/flutter_datetime_picker#50]
Hi!
I really like the package you've created for creating a time picker
However, your documentation for extending and creating a custom picker is not at all present.
Please create documentation for creating a custom picker in your README.md in pub.dev and on github. 

The lack of documentation for creating a custom picker is frustrating.

**Comment by Realank** [comment]
thanks for your great suggestion, I've add a example to show how to customize your own picker model, please pull new code to review, thanks again
