### ISSUE TITLE
Reorder ShowDatePicker

### ISSUE THREAD

**Issue by byronferguson** [Realank/flutter_datetime_picker#55]
Is this currently doable?

**Comment by Realank** [comment]
Hi, how to reorder? could you plz tell me in detail?

**Comment by byronferguson** [comment]
The current display order for the spinners is "YEAR / MONTH / DAY". While that makes perfect sense. In the US the most common order is "MONTH / DAY / YEAR", and I know in Europe they often use "DAY / MONTH / YEAR".

**Comment by Realank** [comment]
aha, as I mentioned in readme, you can customize your own picker model, so that you can reorder the year / month / day, and even change the content to display
