### ISSUE TITLE
AM/PM functionality?

### ISSUE THREAD

**Issue by rgbinnovation** [Realank/flutter_datetime_picker#57]
Hi,

Does this package feature AM/PM functionality, or is it only 24 hour times? Can't find anything to make it AM/PM.

**Comment by rgbinnovation** [comment]
Have tried making a Custom Model, but the second picker (which I am making into the AM/PM always just generated a huge list of PMs.. And results still becomes seconds?

**Comment by rgbinnovation** [comment]
Have also posted about this on Stackoverflow, but no luck yet: https://stackoverflow.com/questions/57016056/flutter-flutter-datetime-picker-package-to-generate-am-pm

**Comment by Realank** [comment]
hi, you should override rightStringAtIndex() method in your custom model, don't override _fillRightLists() method
