### ISSUE TITLE
Add min time to show DateTimepicker

### ISSUE THREAD

**Issue by m4kz** [Realank/flutter_datetime_picker#58]
it will be useful to be able to set minTime also for datetimepicker, as it currently allows picking dates in the past.

**Comment by carotkut94** [comment]
Yes. this would be the thing needed, as by adding the min time in the dateTimePicker we can avoid selecting past dates.

**Comment by QuentinSc** [comment]
Waiting for that too :)

**Comment by shrutikateiosys** [comment]
hey i am also waiting for this. please help to hide past dates.

**Comment by ad-on-is** [comment]
minTime and mixTime pls

**Comment by Realank** [comment]
hi all, I've added min/max time for date time picker. Now, the maxTime or minTime is an optional parameter. It's very complicated to implement it, please have a try. if there is any bug, please feel free to tell me.
