### ISSUE TITLE
how to chose only Date without Time

### ISSUE THREAD

**Issue by thewama33** [Realank/flutter_datetime_picker#60]
when i chose only date without time  in TextField it goes like that

12-5-2019 00:00:00:00

i want to remove this zeros 

> `_showDateTimePicker() {
    DatePicker.showDatePicker(context, showTitleActions: true,
        onConfirm: (date) {
      setState(
        () {
          _signupBirthController.text = date.toString();
        },
      );
    }, currentTime: null);
  }`

**Comment by Realank** [comment]
format the print of DateTime class
