### ISSUE TITLE
[Question] - Is it possible to implement it in page

### ISSUE THREAD

**Issue by angel1st** [Realank/flutter_datetime_picker#63]
Hi there,
Would you please let me know if the picker can be implemented in page e.g. in [this datetime picker](https://github.com/wuzhendev/flutter-cupertino-date-picker)? The reason I would go with yours is the number of supported locales.
Thanks!

**Comment by Realank** [comment]
sorry, it can't, but you can abstract some codes in this package to achieve that, thanks
