### ISSUE TITLE
Landscape mode / SafeArea

### ISSUE THREAD

**Issue by savadodesigns** [Realank/flutter_datetime_picker#67]
Is there a way to use SafeArea for the date/time pickers in landscape mode?

<img width="879" alt="Schermafbeelding 2019-09-03 om 19 58 53" src="https://user-images.githubusercontent.com/21218628/64196993-4e3b6b80-ce85-11e9-829d-e8fb0c2917ea.png">

**Comment by rdev-software** [comment]
Even for portrait mode it would be useful!

**Comment by Realank** [comment]
added in latest codes
