### ISSUE TITLE
how can i change background color of dialog?

### ISSUE THREAD

**Issue by LinoAlejandro** [Realank/flutter_datetime_picker#69]

**Comment by mesunnysaini** [comment]
@LinoAlejandro 

You can change it by changing the **DatePickerTheme** -> **backgroundColor: Colors.white,**

You can replace the **white** color with your color.

**Comment by Realank** [comment]
@mesunnysaini thanks for your reply

**Comment by fauzi2107** [comment]
hi @mesunnysaini i found date picker theme, but how and where should i write that?
i already try this
<img width="532" alt="Screen Shot 2019-10-22 at 16 35 26" src="https://user-images.githubusercontent.com/34369203/67274150-139b9a00-f4ea-11e9-8869-df026f48282b.png">

<img width="308" alt="Screen Shot 2019-10-22 at 16 36 43" src="https://user-images.githubusercontent.com/34369203/67274210-2d3ce180-f4ea-11e9-87d4-e724877f62bc.png">
