### ISSUE TITLE
datetimepicker 除了日期的区间，能否增加一个小时分钟的区间？

### ISSUE THREAD

**Issue by DNetORM** [Realank/flutter_datetime_picker#70]
之前问过这个问题，说是让我自己继承实现，我尝试去弄没有实现出来，我要的功能就是增加一个小时分钟区间，比如上班时间是8:30 到17:30，那么这就是一个区间，无论选择了哪一天，我就只能选择8:30 到17:30的时间，我没能实现这个功能，作者能否去实现一下，加两个参数？因为我觉得这个功能还是比较普遍

**Comment by Realank** [comment]
不好意思，实际开发中的需求千变万化，无法覆盖这么多需求，您可以自己参照代码来实现，只需要新增加一个picker model即可
