### ISSUE TITLE
关于参数名称的建议

### ISSUE THREAD

**Issue by DNetORM** [Realank/flutter_datetime_picker#71]
static void showDatePicker(
    BuildContext context, {
    bool showTitleActions: true,
    DateTime minTime,
    DateTime maxTime,

这里的showDatePicker，minTime和maxTime建议改成minDate和maxDate,会比较确切，因为约定俗成date是日期部分，time表示小时分钟部分

**Comment by Realank** [comment]
因为这里的参数是DateTime类型，所以统一为了time
