### ISSUE TITLE
Different step for minutes

### ISSUE THREAD

**Issue by MatiDeve** [Realank/flutter_datetime_picker#74]
Hi, thanks for this amaizing package! I need to change the steps for minutes to 5 in 5. How can I do that? I had changed the showTimePicker few months ago but I upgrade the packages and I miss my "solution". 
I did these changes on TimePickerModel:

```
_currentMiddleIndex = this.currentTime.minute * 5;
...
@override
  String middleStringAtIndex(int index) {
    if (index >= 0 && index < 60 / 5) {
      return digits(index * 5, 2);
    } else {
      return null;
    }
  }
```

It works well for select, but it fails when I open a TimePicker because it does index = currentMinute * 5 and index is usually greater than 12.

**Comment by Realank** [comment]
I think you should modify the finalTime method to change minute parameter to _currentMiddleIndex * 5

**Comment by hukjordanjanaq** [comment]
@matiasfdevecchi hi, sorry did you figure out?
I'm trying but i can't resolve it.
