### ISSUE TITLE
关于修改年后,只判断了月份正确与否而未判断日期的问题

### ISSUE THREAD

**Issue by wula11** [Realank/flutter_datetime_picker#78]
当结束时间设为19年11月4日时,选了18年12月31后,跳到19年,虽然月正确的跳到了11月,但是日期是为空的

1900-1-1到2019-11-4,2018-12-31跳回19年时,时间自动调整的是2019-11-(空)

**Comment by Realank** [comment]
谢谢你的测试用例，这是一个隐藏特别深的bug，计算第三列的key的时候，使用的是年份index+月份index，但是在2018.12切换到2019.11的时候，其实两者的和不变，已经改变key的计算，年份增加了偏移量，多谢
