### ISSUE TITLE
Only Month and year

### ISSUE THREAD

**Issue by thewama33** [Realank/flutter_datetime_picker#80]
how to show only  Months  and years in the picker  without   Days

**Comment by Realank** [comment]
sorry, it can't , you can customize your own picker model to achieve that. some guy add this feature in TimePickerModel, you can refer to it

**Comment by LinWell** [comment]
void _showDatePicker() {
    DatePicker.showPicker(
      context,
      pickerModel: YearMonthModel (
        currentTime: DateTime.now(),
        maxTime: DateTime.now(),
        minTime: DateTime(2021, 1, 1),
        locale: LocaleType.zh,
      ),
      locale: LocaleType.zh,
      onChanged: (date) {
        print('change $date');
      },
      onConfirm: (date) {
        print('confirm $date');
      },
    );
  }
}

class YearMonthModel  extends DatePickerModel {
  YearMonthModel (
      {DateTime currentTime,
      DateTime maxTime,
      DateTime minTime,
      LocaleType locale})
      : super(
            currentTime: currentTime,
            maxTime: maxTime,
            minTime: minTime,
            locale: locale);

  @override
  List<int> layoutProportions() {
    return [1, 1, 0];
  }
}

**Comment by iremiko** [comment]
> void _showDatePicker() { DatePicker.showPicker( context, pickerModel: YearMonthModel ( currentTime: DateTime.now(), maxTime: DateTime.now(), minTime: DateTime(2021, 1, 1), locale: LocaleType.zh, ), locale: LocaleType.zh, onChanged: (date) { print('change $date'); }, onConfirm: (date) { print('confirm $date'); }, ); } }
> 
> class YearMonthModel extends DatePickerModel { YearMonthModel ( {DateTime currentTime, DateTime maxTime, DateTime minTime, LocaleType locale}) : super( currentTime: currentTime, maxTime: maxTime, minTime: minTime, locale: locale);
> 
> @OverRide List layoutProportions() { return [1, 1, 0]; } }

Hi, I tried this solution but it didn't work

**Comment by leslie0527** [comment]
> > void _showDatePicker() { DatePicker.showPicker( context, pickerModel: YearMonthModel ( currentTime: DateTime.now(), maxTime: DateTime.now(), minTime: DateTime(2021, 1, 1), locale: LocaleType.zh, ), locale: LocaleType.zh, onChanged: (date) { print('change $date'); }, onConfirm: (date) { print('confirm $date'); }, ); } }
> > class YearMonthModel extends DatePickerModel { YearMonthModel ( {DateTime currentTime, DateTime maxTime, DateTime minTime, LocaleType locale}) : super( currentTime: currentTime, maxTime: maxTime, minTime: minTime, locale: locale);
> > @OverRide List layoutProportions() { return [1, 1, 0]; } }
> 
> Hi, I tried this solution but it didn't work

I tried,this is effective    



DatePicker.showPicker(context,
                        showTitleActions: true,
                        pickerModel: YearMonthModel(
                          currentTime: DateTime.now(),
                          maxTime: DateTime.now(),
                          minTime: DateTime(1970, 1, 1),
                          locale: LocaleType.zh,
                        ),
                        locale: LocaleType.zh, onConfirm: (date) {
                      print(date);
                    });


class YearMonthModel extends DatePickerModel {
  YearMonthModel(
      {DateTime currentTime,
      DateTime maxTime,
      DateTime minTime,
      LocaleType locale})
      : super(
            currentTime: currentTime,
            maxTime: maxTime,
            minTime: minTime,
            locale: locale);

  @override
  List<int> layoutProportions() {
    return [1, 1, 0];
  }
}
