### ISSUE TITLE
Null error that has to do with context

### ISSUE THREAD

**Issue by tsweu** [Realank/flutter_datetime_picker#83]
Hello, 

I am getting an error when trying to use your code. 

`The getter 'modalBarrierDismissLabel' was called on null.
Receiver: null
Tried calling: modalBarrierDismissLabel`

I used a Builder to get a new context but that did not help. I think the line that is causing the problem is `MaterialLocalizations.of(context).modalBarrierDismissLabel,` and perhaps that does not work because I am not using a MaterialApp (I am using CupertinoApp). Is that right? 

Do you have any suggestions on how to proceed?

**Comment by Realank** [comment]
sorry, this package is designed to use MaterialApp, I think wrap a MaterialLocalizations or something else may solve this issue, but I didn't try. If you've solved this issue, please share to me, thanks
