### ISSUE TITLE
calendar in Japanese show view is not right 

### ISSUE THREAD

**Issue by RommiPlus** [Realank/flutter_datetime_picker#85]
if there has unit in year/month/day，there should all be. Otherwise, it should all not. 
Now, in Japanese, year is number, month has unit, day is number. That looks not right. Hope fix it soon.

Error photo link：
[error photo](https://ibb.co/7QD4w6Q)

**Comment by shinriyo** [comment]
I tried but correct.
share your version and code.
<img width="544" alt="Screen Shot 2019-12-05 at 1 39 24" src="https://user-images.githubusercontent.com/396927/70161931-31bb0380-1700-11ea-9491-d40602085de0.png">

```
            FlatButton(
              onPressed: () {
                DatePicker.showDatePicker(
                  context,
                  showTitleActions: true,
                  onChanged: (date) {
                    print('change $date in time zone ' +
                        date.timeZoneOffset.inHours.toString());
                  },
                  onConfirm: (date) {
                    print('confirm $date');
                  },
                  currentTime: DateTime(2008, 12, 31, 23, 12, 34),
                  locale: LocaleType.jp,
                );
              },
              child: Text(
                'show date picker (Japanese)',
                style: TextStyle(color: Colors.blue),
              ),
            ),
```

**Comment by RommiPlus** [comment]
I tried source code in this repository, the picker as shown as your photo. But f[lutter_datetime_picker 1.2.8](https://pub.dev/packages/flutter_datetime_picker) is shown as mine.

when i change the reference in pubspec.yaml as follows , it's looks ok.
```
  flutter_datetime_picker: 
    git: https://github.com/Realank/flutter_datetime_picker.git
```

Hope the author can publish this version to pub repository and fix it as soon as possible.
