### ISSUE TITLE
Unexpected range for DateTimePicker

### ISSUE THREAD

**Issue by terrylow** [Realank/flutter_datetime_picker#90]
When uses the same date for minTime & maxTime, the datetime picker will not limit the user from selecting date exceeded the value specified in the maxTime field.

` DatePicker.showDateTimePicker(context,
              minTime: DateTime(2019,12,10,8),
              maxTime: DateTime(2019,12,10,12),
                onChanged: (date){
                print(date);
                }
              );`

**Comment by Realank** [comment]
yes it is, there is a safety check for min&max time, max time should later than min time

**Comment by ziasultan2** [comment]
@Realank  If I put any date for minTime it gives me error except DateTime.now
