### ISSUE TITLE
When currentTime == minTime, the picker will show all datetime range without limiting the min value as expected.

### ISSUE THREAD

**Issue by ronniechew** [Realank/flutter_datetime_picker#92]
When currentTime == minTime, the picker will show all datetime range without limiting the min value as expected.

**Comment by Realank** [comment]
In current codes, you shouldn't set currentTime == minTime, it will ignore the minTime, but I think you are right, currentTime can equal to minTime, I will change the codes, please wait for next version

**Comment by amitkhairnar44** [comment]
@Realank Is this issue fixed?

**Comment by magax** [comment]
Hey guys, I am still facing this issue. This shouldn't be closed, I'm currently using an ugly workaround to make it work properly :/

**Comment by aris-1** [comment]
Issue still there, why is this closed?
