### ISSUE TITLE
showDatePicker always return null, should return onConfirm result

### ISSUE THREAD

**Issue by sadollomania** [Realank/flutter_datetime_picker#94]
showDatePicker says it returns Future<dynamic>but it always return null.  'Done' button should be like this in "_renderTitleActionsView" function

Container(
            height: theme.titleHeight,
            child: CupertinoButton(
              pressedOpacity: 0.3,
              padding: EdgeInsets.only(right: 16, top: 0),
              child: Text(
                '$done',
                style: theme.doneStyle,
              ),
              onPressed: () {
                dynamic retVal;
                if (widget.route.onConfirm != null) {
                  retVal = widget.route.onConfirm(widget.pickerModel.finalTime());
                }
                Navigator.pop(context, retVal);
              },
            ),
          )

**Comment by Realank** [comment]
please use onConfirm callback function to get the data time, instead of using returned value, or you can use next version of this packages, a PR to fix the return value has been merged
